---
# tasks file for php
- name: Install php 7
  yum: "name={{ item }} state=present"
  with_items:
    - php72
    - php72-gd
    - php72-imap
    - php72-mbstring
    - php72-mysqlnd
    - php72-opcache
    - php72-pdo
    - php72-pecl-apcu
  notify: restart Apache 
- name: Upload index.php to remote web directory
  copy: src=index.php dest=/var/www/html owner=ec2-user group=ec2-user
